### ISSUE TITLE
Pre-Compiled Binaries

### ISSUE THREAD

**Issue by breakthetargets** [vladikcomper/md-modules#1]
Hey, in the README you stated that pre-compiled binaries are available, but I actually just noticed that they seem to be ignored in the .gitignore

**Comment by vladikcomper** [comment]
Hey, and thank you for creating the first-ever issue here :)

README doesn't lie, in fact: pre-compiled binaries of utilities and assemblers can be found here: https://github.com/vladikcomper/md-modules/tree/master/modules/exec

And of course you can also get them (albeit quite outdated at the time of writing) on the Releases page: https://github.com/vladikcomper/md-modules/releases/

Yes, if you look for each utility source code (in `utilities` directory), its executable is indeed ignored, because it's a common practice. However, these utilities are needed to build modules (in `modules` directory), which is why they are copied by build scripts in `modules/exec` for convenience.

Unfortunately, Windows executables are quite outdated at the time of writing, and I cannot fix this right now as I don't have a Windows machine. Only Linux binaries are up-to-date.

**Comment by breakthetargets** [comment]
Oh I apologize, I should have looked actually further than I have! Thank you for the fast response.
