### ISSUE TITLE
Build failure in Gmake Cygwin 

### ISSUE THREAD

**Issue by OrionNavattan** [vladikcomper/md-modules#25]
Given my lack of experience with this, I'm not sure if this is actually a problem with your code or Makefiles, or something on my end. That said, my attempts to build version 2.5 using GMake installed via Cygwin have failed, with the compiler complaining that it cannot find one of the includes for convsym. Seems like there might be something up with the handling of wildcards, but I honestly have no idea.

<img width="921" alt="Screenshot 2023-08-17 at 12 47 42" src="https://github.com/vladikcomper/md-modules/assets/103385399/992478e9-ea92-4d5a-9748-e1049e564110">

**Comment by vladikcomper** [comment]
I'm not entirely sure where this error is coming from (it fails to find a header file that is clearly there), but I've spotted 2 issues so far:

1. __You have spaces in your full path (`.../game disasemblies/MD Libraries/Error Handlers/...`);__

   Makefiles don't tolerate spaces in many cases, because whenever the full path is substituted, spaces act like file list separators (really unfortunate, but the technology is _old_). This isn't an issue for building `utils` though, but you won't get far with building `modules` this way.

2. __You're running a Windows-specific Makefile in Bash instead of Cmd.__

   This is indicated by `md: No such file or directory`. `md` (*m*ake *d*irectory) is a DOS/Windows utility, but for Bash with Unix binutils, you'd use `mkdir`.

   You need to run `make -f Makefile.win` from Cmd.exe (Windows native Command line). But make sure `make`, `python` and `gcc` are available there (should be included in `PATH` environment variable). The easiest solution on Windows (that I know of) is to use Chocolatey package manager to install everything:

   ```sh
   choco install mingw python3 make
   ```

   I don't run Windows as my main OS, so I only tested that. Not sure about other ways, but one can probably use WSL/WSL2 to run Linux build scripts without a hassle.

   ... But if you use Cygwin, you probably don't need Windows build scripts as well! It aims to provide fully POSIX-compatible environment, meaning you can stick to native Linux/Unix build system. Technically, you're supposed to run just `make` (will pick up `Makefile` instead of `Makefile.win`) and it _should_ do the job for you... except it will probably build only `utils` and error out on `modules`, since it relies on `wine` :)

   I don't recommend using Cygwin here, because it's essentially a POSIX emulator with a ton of overhead. And I don't use POSIX calls/API anywhere, only the standard C++ library, so my code is fully cross platform. Try out MinGW instead.

**Comment by OrionNavattan** [comment]
Went ahead and tried MinGW. Still fails, this time because it can't find the Python install (possibly related to having an older version already installed?). Ultimately though I ended up not needing to build it; the preassembled bundle ended up working for what I needed (a bit perfect reference for putting together a fully-source assembled version as part of the process of rebasing my Mega CD Error Handler).
